### ISSUE TITLE
ISO files

### ISSUE THREAD

**Issue by fandangos** [BlkChockr/nzbget-stream#2]
Hi! Hope you're travel around the world has been nice!

I'm trying several solutions to stream content from usenet and your script works for almost everything. 
For compressed content that often don't show an extension when being streamed I figured I just had to add *.* as one of the video files format.

But when it comes to ISO files it won't start any kind of streaming. I have an OPPO BDP with CFW that can play ISO from the network and streaming ISO files would be amazing. 

Or even on PC it could be used to open Gizmo Drive, mount the ISO and play with PowerDVD. 

Would it be possible for this to be added?

**Comment by c4tz** [comment]
Hi! I'm glad you use and like my script. :)

Have you tried adding `.iso` to the video extensions? That should at least extract the incomplete ISO-File from the archive, so that you *maybe* can stream it with your player. It might not work though, because ISO is just a container with files in it (which would have to be fully downloaded first, I think).

If you try that, you should change line 138 to:

```
#openMediaFile(STREAM_FILE)
```
so that the script doesn't try to open it on your PC.

Or did you mean partially extract **from** an ISO-File you are downloading?

**Comment by fandangos** [comment]
Thank you for replying. 

I`m downloading a nzb file that has multi-part rar files and inside those it's a iso file. 

Adding .iso, ISO, even * or *.*, nothing works.

Tried with several nzb files, it just won't start or do anything at all, no error from NZBGet.

And streaming ISO works with NZBDrive but NZBDrive does not support password protected files, which is almost 90% of good releases. 
So I have high hopes that this would also work with your script and if it does, it will be fantastic :)

**Comment by c4tz** [comment]
Did you have a look at the InterDir-folder where the files are stored before extraction? When streaming, there will be a "stream"-folder insider the .nzb's respective folder. That's where the script will put the partially extracted files.

For clairification:

```
InterDir
|--YOURNZBNAME
   |--stream
      |--stream.iso
```

Should be the tree while downloading if you put `.iso` in the extension-array.

**Comment by fandangos** [comment]
Yes, I've checked. 

It outputs nothing. 
Even looking at windows processes there's no unrar or anything going on. 

It works for everything else (video related).
It even tries for blu-ray folder structures and outputs a .m2ts - a broken one but it does.

**Comment by fandangos** [comment]
After 10 different NZB files, found one that worked :)

So, you were right, it starts to extract the iso file. 
The NZB was out of order (the one that worked) but after sorting and downloading the first part it worked. 

But many other NZB files just won't start the unpacking.

**Comment by fandangos** [comment]
And ISO playback doesn't work :(
The player just shows loading...

Well, it was worth a shot.

**Comment by c4tz** [comment]
Oh, I'm sorry to hear/read that.

Yes, as I wrote in the description the .rar-files inside the .nzb must the sorted, because it makes no sense to extract the fourth part of a video file first, for example. Also, I think that extracting multipart-archives is not possible if the first/previous parts are missing.

I hope you still enjoy streaming your favorite vacation videos from the usenet, though. ;)

Please close this issue if you don't have any other question regarding ISO-file streaming.

**Comment by fandangos** [comment]
Ok, thank you.
