### ISSUE TITLE
If Category ==

### ISSUE THREAD

**Issue by wtf911** [BlkChockr/nzbget-stream#3]
Would it be possible to add the if category == part of it? So I could have it only work on files I put in a certain category? Thank you for such a cool script!

**Comment by c4tz** [comment]
I'm glad you like it! :)

I implemented this feature in its own branch for you:

https://github.com/BlkChockr/nzbget-stream/blob/category/stream.py

But I'm wondering if there is actually any need for it, because with this approach you need to create a new category, set it on each .nzb and you won't be able to choose another one, like "Movie", e.g.

I think the more practical idea is to just leave it as is and only activate the script for certain downloads, in their post-processing options, like this:

![bildschirmfoto_2017-04-05_13-16-25](https://cloud.githubusercontent.com/assets/4035667/24703187/704f702a-1a02-11e7-9fbe-77d0dede43e3.png)

That way, you could still set another category AND stream while downloading.

What do you think about this?

**Comment by wtf911** [comment]
Wow thank you! I really appreciate your quick and helpful response. I did not realize it was possible to click the download > click post-process > and then from there have the ability to use things on a per download basis. You are right, that way is more useful! Thank you again!
